name: Curl Test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Run curl test
      run: |
        curl -X 'GET' \
        'http://127.0.0.1:8000/chatgpt/{prompt}?your_question=how%20are%20you%3F' \
        -H 'accept: application/json'
        
    - name: Stop the FastAPI server
      run: lsof -ti :8000 | xargs kill -9 || true
      
