name: FastAPI Workflow

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        pip install pytest
        pip install httpx

    - name: Static Code Linting with flake8
      env:
        CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Unit Testing with pytest
      env:
        CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
      run: |
        pytest
