name: FastAPI Workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start FastAPI with Chatbot
      env:
        CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
      run: |
        python3 -m uvicorn main:app --reload
        
    - name: test Curl respond
      run: |
        curl -X 'GET' \
        'http://127.0.0.1:8000/chatgpt/{prompt}?your_question=how%20are%20you%3F' \
        -H 'accept: application/json'
